export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/options';
import PolygonMarket from '@/app/models/PolygonMarket.model';
import Auctions from '@/app/models/auction.model';
import connectToDB from '@/app/lib/mongoose';

export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    if (session.user.role !== 'admin' && session.user.role !== 'owner') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectToDB();

    const markets = await PolygonMarket.find({}).sort({ createdAt: -1 }).lean();

    const enriched = await Promise.all(
      markets.map(async (market: any) => {
        let auctionTitle = 'Unknown Auction';
        let auctionPageUrl = '';
        let auctionDeadline: string | null = null;

        try {
          const auction = await Auctions.findById(market.auctionId).select('title page_url sort').lean() as any;
          if (auction) {
            auctionTitle = auction.title || auctionTitle;
            auctionPageUrl = auction.page_url || '';
            auctionDeadline = auction.sort?.deadline ? new Date(auction.sort.deadline).toISOString() : null;
          }
        } catch {
          // auction lookup failed — leave defaults
        }

        return {
          _id: market._id.toString(),
          auctionId: market.auctionId,
          auctionTitle,
          auctionPageUrl,
          auctionDeadline,
          status: market.status,
          predictedPrice: market.predictedPrice,
          totalVolume: market.totalVolume,
          totalLiquidity: market.totalLiquidity,
          contractAddress: market.contractAddress,
          autoGenerated: market.autoGenerated || false,
          trendScore: market.trendScore,
          createdAt: market.createdAt ? new Date(market.createdAt).toISOString() : '',
        };
      })
    );

    return NextResponse.json({ markets: enriched, total: enriched.length });
  } catch (error) {
    console.error('[GET /api/admin/polygon-markets]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
