"use client";
import React, { useEffect, useState } from "react";
import { BeatLoader } from "react-spinners";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/app/ui/components/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/app/ui/components/table";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/app/ui/components/dialog";
import { Badge } from "@/app/ui/components/badge";
import { Button } from "@/app/ui/components/button";
import { Label } from "@/app/ui/components/label";
import { Input } from "@/app/ui/components/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/app/ui/components/select";
import { Textarea } from "@/app/ui/components/textarea";
import { formatDate } from "@/app/helpers/utils";
import { ExternalLink, Pencil, Plus, TrendingUp } from "lucide-react";

interface MarketRow {
  _id: string;
  auctionId: string;
  auctionTitle: string;
  auctionPageUrl: string;
  auctionDeadline: string | null;
  status: "PENDING" | "ACTIVE" | "RESOLVED" | "DISPUTED";
  predictedPrice: number;
  question?: string;
  closesAt?: string;
  totalVolume: number;
  totalLiquidity: number;
  contractAddress: string;
  autoGenerated: boolean;
  trendScore?: number;
  createdAt: string;
}

interface AuctionOption {
  _id: string;
  title: string;
  sort?: { price?: number; deadline?: string };
  avg_predicted_price?: number;
}

const STATUS_COLORS: Record<string, string> = {
  ACTIVE: "bg-green-500/20 text-green-400 border-green-500/30",
  PENDING: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  RESOLVED: "bg-blue-500/20 text-blue-400 border-blue-500/30",
  DISPUTED: "bg-red-500/20 text-red-400 border-red-500/30",
};

const USDollar = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
});

export default function MarketsPage() {
  const [markets, setMarkets] = useState<MarketRow[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [activeAuctions, setActiveAuctions] = useState<AuctionOption[]>([]);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [createForm, setCreateForm] = useState({
    auctionId: "",
    question: "",
    endDate: "",
    initialLiquidity: 0,
  });
  const [createLoading, setCreateLoading] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);
  const [statusUpdating, setStatusUpdating] = useState<Record<string, boolean>>({});
  const [error, setError] = useState<string | null>(null);

  // Edit dialog state
  const [editMarket, setEditMarket] = useState<MarketRow | null>(null);
  const [editForm, setEditForm] = useState({ predictedPrice: "", question: "", closesAt: "" });
  const [editLoading, setEditLoading] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);

  const fetchMarkets = async () => {
    try {
      const res = await fetch("/api/admin/polygon-markets");
      const data = await res.json();
      if (res.ok) {
        setMarkets(data.markets || []);
      } else {
        setError(data.error || "Failed to load markets");
      }
    } catch {
      setError("Network error loading markets");
    } finally {
      setIsLoading(false);
    }
  };

  const fetchActiveAuctions = async () => {
    try {
      const res = await fetch("/api/auctions/filter?isPlatformTab=true&limit=100");
      const data = await res.json();
      if (res.ok) {
        setActiveAuctions(data.cars || []);
      }
    } catch {
      // non-fatal
    }
  };

  useEffect(() => {
    fetchMarkets();
    fetchActiveAuctions();
  }, []);

  const handleAuctionSelect = (auctionId: string) => {
    const auction = activeAuctions.find((a) => a._id === auctionId);
    if (!auction) return;

    const predictedPrice = auction.avg_predicted_price || auction.sort?.price || 0;
    const autoQuestion = `Will the ${auction.title} sell for more than ${USDollar.format(predictedPrice)}?`.slice(0, 200);

    let endDate = "";
    if (auction.sort?.deadline) {
      const deadline = new Date(auction.sort.deadline);
      const endDateObj = new Date(deadline.getTime() - 2 * 60 * 60 * 1000);
      endDate = endDateObj.toISOString().slice(0, 16);
    }

    setCreateForm((prev) => ({ ...prev, auctionId, question: autoQuestion, endDate }));
  };

  const handleCreateMarket = async () => {
    setCreateLoading(true);
    setCreateError(null);
    try {
      const res = await fetch("/api/admin/polygon-markets/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          auctionId: createForm.auctionId,
          question: createForm.question,
          endDate: createForm.endDate ? new Date(createForm.endDate).toISOString() : "",
          initialLiquidity: createForm.initialLiquidity,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        setCreateError(data.error || "Failed to create market");
        return;
      }
      setShowCreateDialog(false);
      setCreateForm({ auctionId: "", question: "", endDate: "", initialLiquidity: 0 });
      await fetchMarkets();
    } catch {
      setCreateError("Network error");
    } finally {
      setCreateLoading(false);
    }
  };

  const handleStatusChange = async (marketId: string, newStatus: string) => {
    setStatusUpdating((prev) => ({ ...prev, [marketId]: true }));
    try {
      await fetch(`/api/admin/polygon-markets/${marketId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: newStatus }),
      });
      setMarkets((prev) =>
        prev.map((m) =>
          m._id === marketId ? { ...m, status: newStatus as MarketRow["status"] } : m
        )
      );
    } catch {
      // non-fatal
    } finally {
      setStatusUpdating((prev) => ({ ...prev, [marketId]: false }));
    }
  };

  const openEditDialog = (market: MarketRow) => {
    setEditMarket(market);
    setEditForm({
      predictedPrice: String(market.predictedPrice || ""),
      question: market.question || "",
      closesAt: market.closesAt
        ? new Date(market.closesAt).toISOString().slice(0, 16)
        : market.auctionDeadline
          ? new Date(market.auctionDeadline).toISOString().slice(0, 16)
          : "",
    });
    setEditError(null);
  };

  const handleEditSave = async () => {
    if (!editMarket) return;
    setEditLoading(true);
    setEditError(null);

    const body: Record<string, unknown> = {};
    const newPrice = parseFloat(editForm.predictedPrice);
    if (!isNaN(newPrice) && newPrice > 0 && newPrice !== editMarket.predictedPrice) {
      body.predictedPrice = newPrice;
    }
    if (editForm.question && editForm.question !== editMarket.question) {
      body.question = editForm.question;
    }
    if (editForm.closesAt) {
      const newDate = new Date(editForm.closesAt).toISOString();
      if (newDate !== editMarket.closesAt) {
        body.closesAt = newDate;
      }
    }

    if (Object.keys(body).length === 0) {
      setEditMarket(null);
      setEditLoading(false);
      return;
    }

    try {
      const res = await fetch(`/api/admin/polygon-markets/${editMarket._id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!res.ok) {
        setEditError(data.error || "Failed to update market");
        return;
      }
      // Update local state
      setMarkets((prev) =>
        prev.map((m) =>
          m._id === editMarket._id
            ? {
                ...m,
                predictedPrice: data.market.predictedPrice ?? m.predictedPrice,
                question: data.market.question ?? m.question,
                closesAt: data.market.closesAt ?? m.closesAt,
              }
            : m
        )
      );
      setEditMarket(null);
    } catch {
      setEditError("Network error");
    } finally {
      setEditLoading(false);
    }
  };

  const stats = {
    total: markets.length,
    active: markets.filter((m) => m.status === "ACTIVE").length,
    pending: markets.filter((m) => m.status === "PENDING").length,
    volume: markets.reduce((sum, m) => sum + m.totalVolume, 0),
  };

  return (
    <div className="mt-4 p-4">
      {/* Header */}
      <div className="mb-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <TrendingUp className="h-7 w-7 text-[#F2CA16]" />
          <h2 className="text-2xl font-bold">Prediction Markets</h2>
        </div>
        <Button
          onClick={() => setShowCreateDialog(true)}
          className="flex items-center gap-2 bg-[#F2CA16] text-black hover:bg-[#F2CA16]/90"
        >
          <Plus className="h-4 w-4" />
          Create Market
        </Button>
      </div>

      {/* Stats */}
      <div className="mb-6 grid grid-cols-2 gap-4 md:grid-cols-4">
        {[
          { label: "Total Markets", value: stats.total },
          { label: "Active", value: stats.active },
          { label: "Pending", value: stats.pending },
          { label: "Total Volume", value: USDollar.format(stats.volume) },
        ].map((stat) => (
          <Card key={stat.label} className="bg-[#13202D]">
            <CardContent className="p-4">
              <div className="text-sm text-gray-400">{stat.label}</div>
              <div className="mt-1 text-2xl font-bold">{stat.value}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Markets Table */}
      <Card className="bg-[#13202D]">
        <CardHeader>
          <CardTitle>All Markets</CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex justify-center py-12">
              <BeatLoader color="#F2CA16" />
            </div>
          ) : error ? (
            <div className="py-8 text-center text-red-400">{error}</div>
          ) : markets.length === 0 ? (
            <div className="py-12 text-center text-gray-400">
              No markets yet.{" "}
              <button
                onClick={() => setShowCreateDialog(true)}
                className="text-[#F2CA16] underline"
              >
                Create one
              </button>{" "}
              or{" "}
              <span className="font-mono text-xs text-gray-500">
                npm run db:seed-markets
              </span>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Auction</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Predicted Price</TableHead>
                  <TableHead>Volume</TableHead>
                  <TableHead>Score</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {markets.map((market) => (
                  <TableRow key={market._id}>
                    <TableCell className="max-w-[220px]">
                      <div className="line-clamp-2 font-medium">{market.auctionTitle}</div>
                      <div className="mt-1 flex items-center gap-2">
                        {market.auctionPageUrl && (
                          <a
                            href={market.auctionPageUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center gap-1 text-xs text-[#F2CA16] hover:underline"
                          >
                            <ExternalLink className="h-3 w-3" />
                            BaT
                          </a>
                        )}
                        {market.autoGenerated && (
                          <span className="inline-block rounded bg-purple-500/20 px-1.5 py-0.5 text-[10px] text-purple-300">
                            auto
                          </span>
                        )}
                      </div>
                      {market.question && (
                        <div className="mt-1 text-xs text-gray-500 line-clamp-1">{market.question}</div>
                      )}
                    </TableCell>
                    <TableCell>
                      <Badge className={STATUS_COLORS[market.status] || ""}>
                        {market.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="font-mono">
                      {USDollar.format(market.predictedPrice)}
                    </TableCell>
                    <TableCell className="font-mono">
                      {USDollar.format(market.totalVolume)}
                    </TableCell>
                    <TableCell className="font-mono text-sm text-gray-400">
                      {market.trendScore !== undefined ? market.trendScore.toFixed(2) : "—"}
                    </TableCell>
                    <TableCell className="text-sm text-gray-400">
                      {market.createdAt ? formatDate(new Date(market.createdAt)) : "—"}
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => openEditDialog(market)}
                          className="h-8 w-8 p-0 text-gray-400 hover:text-[#F2CA16]"
                          title="Edit price, question, end date"
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        {statusUpdating[market._id] ? (
                          <BeatLoader size={6} color="#F2CA16" />
                        ) : (
                          <Select
                            value={market.status}
                            onValueChange={(val) => handleStatusChange(market._id, val)}
                          >
                            <SelectTrigger className="w-32 bg-[#1E2A36]">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="PENDING">PENDING</SelectItem>
                              <SelectItem value="ACTIVE">ACTIVE</SelectItem>
                              <SelectItem value="RESOLVED">RESOLVED</SelectItem>
                              <SelectItem value="DISPUTED">DISPUTED</SelectItem>
                            </SelectContent>
                          </Select>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Create Market Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent className="bg-[#13202D] sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Create Prediction Market</DialogTitle>
          </DialogHeader>

          <div className="space-y-4">
            {createError && (
              <div className="rounded border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-400">
                {createError}
              </div>
            )}

            <div className="space-y-1.5">
              <Label>Auction</Label>
              <Select onValueChange={handleAuctionSelect} value={createForm.auctionId}>
                <SelectTrigger className="bg-[#1E2A36]">
                  <SelectValue placeholder="Select an auction..." />
                </SelectTrigger>
                <SelectContent className="max-h-64">
                  {activeAuctions.map((a) => (
                    <SelectItem key={a._id} value={a._id}>
                      {a.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1.5">
              <Label>Market Question</Label>
              <Textarea
                value={createForm.question}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setCreateForm((prev) => ({ ...prev, question: e.target.value }))}
                placeholder="Will this car sell for more than $X?"
                className="bg-[#1E2A36]"
                rows={3}
                maxLength={200}
              />
              <div className="text-right text-xs text-gray-500">
                {createForm.question.length}/200
              </div>
            </div>

            <div className="space-y-1.5">
              <Label>Market End Date</Label>
              <Input
                type="datetime-local"
                value={createForm.endDate}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setCreateForm((prev) => ({ ...prev, endDate: e.target.value }))}
                className="bg-[#1E2A36]"
              />
              <p className="text-xs text-gray-500">Must be before the auction deadline</p>
            </div>

            <div className="space-y-1.5">
              <Label>Initial Liquidity (optional)</Label>
              <Input
                type="number"
                min={0}
                value={createForm.initialLiquidity}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                  setCreateForm((prev) => ({ ...prev, initialLiquidity: Number(e.target.value) }))
                }
                className="bg-[#1E2A36]"
                placeholder="0"
              />
            </div>
          </div>

          <DialogFooter className="mt-2">
            <Button
              variant="outline"
              className="border-gray-600 text-gray-300 hover:bg-gray-700"
              onClick={() => setShowCreateDialog(false)}
              disabled={createLoading}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreateMarket}
              disabled={createLoading || !createForm.auctionId || !createForm.question || !createForm.endDate}
              className="bg-[#F2CA16] text-black hover:bg-[#F2CA16]/90"
            >
              {createLoading ? <BeatLoader size={8} color="black" /> : "Create Market"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Market Dialog */}
      <Dialog open={!!editMarket} onOpenChange={(open) => !open && setEditMarket(null)}>
        <DialogContent className="bg-[#13202D] sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Edit Market</DialogTitle>
          </DialogHeader>

          {editMarket && (
            <div className="space-y-4">
              <div className="rounded bg-[#1E2A36] p-3">
                <div className="text-sm font-medium">{editMarket.auctionTitle}</div>
                <div className="mt-1 text-xs text-gray-400">ID: {editMarket._id}</div>
              </div>

              {editError && (
                <div className="rounded border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-400">
                  {editError}
                </div>
              )}

              <div className="space-y-1.5">
                <Label>Predicted Price ($)</Label>
                <Input
                  type="number"
                  min={1}
                  step={100}
                  value={editForm.predictedPrice}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                    setEditForm((prev) => ({ ...prev, predictedPrice: e.target.value }))
                  }
                  className="bg-[#1E2A36] font-mono"
                  placeholder="e.g. 45000"
                />
                <p className="text-xs text-gray-500">
                  Current: {USDollar.format(editMarket.predictedPrice)}
                </p>
              </div>

              <div className="space-y-1.5">
                <Label>Market Question</Label>
                <Textarea
                  value={editForm.question}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                    setEditForm((prev) => ({ ...prev, question: e.target.value }))
                  }
                  className="bg-[#1E2A36]"
                  rows={3}
                  maxLength={200}
                />
                <div className="text-right text-xs text-gray-500">
                  {editForm.question.length}/200
                </div>
              </div>

              <div className="space-y-1.5">
                <Label>End Date</Label>
                <Input
                  type="datetime-local"
                  value={editForm.closesAt}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                    setEditForm((prev) => ({ ...prev, closesAt: e.target.value }))
                  }
                  className="bg-[#1E2A36]"
                />
              </div>
            </div>
          )}

          <DialogFooter className="mt-2">
            <Button
              variant="outline"
              className="border-gray-600 text-gray-300 hover:bg-gray-700"
              onClick={() => setEditMarket(null)}
              disabled={editLoading}
            >
              Cancel
            </Button>
            <Button
              onClick={handleEditSave}
              disabled={editLoading}
              className="bg-[#F2CA16] text-black hover:bg-[#F2CA16]/90"
            >
              {editLoading ? <BeatLoader size={8} color="black" /> : "Save Changes"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
