export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { withCronAuth } from '@/app/lib/cronAuth';
import connectDB from '@/app/lib/mongoose';
import Auctions from '@/app/models/auction.model';
import PolygonMarket from '@/app/models/PolygonMarket.model';
import { createAuditLog } from '@/app/lib/auditLogger';
import { computeTrendScore } from '@/app/lib/trendScorer';
import { computePredictedPrice } from '@/app/lib/predictedPriceEngine';
import { buildMarketQuestion, roundToNearest500 } from '@/app/lib/marketQuestionBuilder';
import crypto from 'crypto';

export const GET = withCronAuth(async (req: NextRequest) => {
  try {
    await connectDB();

    const MIN_SCORE = parseFloat(process.env.AUTO_MARKET_MIN_SCORE || '0.40');
    const MAX_PER_DAY = parseInt(process.env.AUTO_MARKET_MAX_PER_DAY || '5');
    const MAX_PER_RUN = parseInt(process.env.AUTO_MARKET_MAX_PER_RUN || '3');
    const MAX_GEMINI = parseInt(process.env.AUTO_MARKET_MAX_GEMINI_CALLS || '5');

    // Daily cap check
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    const todayCount = await PolygonMarket.countDocuments({
      autoGenerated: true,
      createdAt: { $gte: todayStart },
    });

    if (todayCount >= MAX_PER_DAY) {
      return NextResponse.json(
        { message: 'Daily auto-market cap reached', todayCount, limit: MAX_PER_DAY },
        { status: 200 }
      );
    }

    const canCreate = Math.min(MAX_PER_DAY - todayCount, MAX_PER_RUN);

    // Candidate query — live auctions with >48h remaining.
    // Note: we intentionally do NOT filter on isActive. The scraper writes
    // new auctions with isActive=false; the only records with isActive=true
    // are historical/manually-flagged docs and all already ended. Using
    // `ended: false` is the correct "is this auction currently live" check.
    const minDeadline = new Date(Date.now() + 48 * 60 * 60 * 1000);
    const candidates = await Auctions.find({
      ended: { $ne: true },
      'sort.deadline': { $gt: minDeadline },
      'sort.bids': { $gte: 2 },
      'sort.price': { $gt: 1000 },
    })
      .sort({ 'sort.bids': -1, views: -1 })
      .limit(20)
      .lean();

    // Dedup: filter out auctions that already have markets
    const auctionIds = candidates.map((a: any) => a._id.toString());
    const existingMarkets = await PolygonMarket.find({
      auctionId: { $in: auctionIds },
    }).select('auctionId').lean() as any[];
    const existingSet = new Set(existingMarkets.map((m) => m.auctionId));

    const deduped = candidates.filter((a: any) => !existingSet.has(a._id.toString()));

    // Score and filter
    const scored = deduped
      .map((a: any) => ({ auction: a, score: computeTrendScore(a) }))
      .filter(({ score }) => score >= MIN_SCORE)
      .sort((a, b) => b.score - a.score)
      .slice(0, canCreate);

    const geminiCallsUsed = { count: 0 };
    const created: any[] = [];
    const errors: any[] = [];

    for (const { auction, score } of scored) {
      try {
        const auctionId = (auction as any)._id.toString();
        const predictedPrice = await computePredictedPrice(auction, geminiCallsUsed, MAX_GEMINI);
        const roundedPrice = roundToNearest500(predictedPrice || (auction as any).sort?.price || 1000);
        const question = buildMarketQuestion(auction, roundedPrice);

        const marketId = crypto.randomBytes(16).toString('hex');
        const contractAddress = `0x${crypto.randomBytes(20).toString('hex')}`;

        const market = await PolygonMarket.create({
          auctionId,
          contractAddress,
          yesTokenId: `token-yes-${marketId}`,
          noTokenId: `token-no-${marketId}`,
          status: 'PENDING',
          predictedPrice: roundedPrice,
          question,
          trendScore: score,
          autoGenerated: true,
          totalVolume: 0,
          totalLiquidity: 0,
          totalFees: 0,
          makerRebatesPaid: 0,
        });

        await createAuditLog({
          userId: 'system',
          username: 'cron:auto-markets',
          userRole: 'system',
          action: 'polygon_market.auto_created',
          resource: 'PolygonMarket',
          resourceId: market._id.toString(),
          method: 'GET',
          endpoint: '/api/cron/auto-markets',
          status: 'success',
          metadata: { auctionId, question, score, predictedPrice: roundedPrice },
          req,
        });

        created.push({
          marketId: market._id.toString(),
          auctionId,
          question,
          score,
          predictedPrice: roundedPrice,
        });
      } catch (e: any) {
        if (e.code === 11000) {
          // duplicate — skip silently
        } else {
          errors.push({ auctionId: (auction as any)._id.toString(), error: e.message });
        }
      }
    }

    return NextResponse.json({
      marketsCreated: created.length,
      candidatesEvaluated: candidates.length,
      dedupedCandidates: deduped.length,
      qualified: scored.length,
      skippedDuplicates: candidates.length - deduped.length,
      geminiCallsUsed: geminiCallsUsed.count,
      created,
      errors,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error('[auto-markets cron error]', error);
    return NextResponse.json(
      { error: 'Internal Server Error', message: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
});
